// config/moodle.js
import axios from 'axios';
import https from 'https';

const WebServiceUrl = process.env.MDL_DOMAIN.replace(/\/+$/, '') + "/webservice/rest/server.php";
const TIMEOUT_MS = Number(process.env.MDL_TIMEOUT_MS || 20000);

/**
 * Axios instance for Moodle
 * - Avoid brotli (br) because it can trigger Z_BUF_ERROR on truncated streams in Heroku
 * - Add timeout to avoid hanging near router 30s
 * - KeepAlive improves stability for repeated calls
 */
const moodleHttp = axios.create({
  timeout: TIMEOUT_MS,
  httpsAgent: new https.Agent({ keepAlive: true }),
  headers: {
    'Accept': 'application/json, text/plain, */*',
    'Accept-Encoding': 'gzip, deflate', // 🚫 no br
    'User-Agent': 'cscampus-enroll/1.0 (moodle client)'
  },
  validateStatus: (s) => s >= 200 && s < 300
});

function isMoodleException(payload) {
  return (
    payload &&
    typeof payload === 'object' &&
    !Array.isArray(payload) &&
    (('exception' in payload) || ('errorcode' in payload))
  );
}

function normalizeEmail(email) {
  return String(email || '').trim().toLowerCase();
}

/**
 * Transport/system errors (Heroku/Moodle network cut, brotli decode issues, etc.)
 */
function isTransientTransportError(err) {
  const code = err?.code;
  const msg = String(err?.message || '');
  return (
    code === 'Z_BUF_ERROR' ||
    code === 'ECONNRESET' ||
    code === 'ETIMEDOUT' ||
    code === 'EPIPE' ||
    msg.includes('unexpected end of file') ||
    msg.includes('socket hang up') ||
    msg.includes('read ECONNRESET')
  );
}

async function sleep(ms) {
  return new Promise(r => setTimeout(r, ms));
}

/**
 * Retry wrapper (use for GETs only)
 */
async function withRetry(fn, { retries = 2, baseDelayMs = 350, label = 'moodle-call' } = {}) {
  let lastErr;
  for (let attempt = 0; attempt <= retries; attempt++) {
    try {
      return await fn();
    } catch (err) {
      lastErr = err;
      const transient = isTransientTransportError(err);
      const last = attempt === retries;

      console.error(`[MOODLE][${label}] failed attempt=${attempt + 1}/${retries + 1}`, {
        code: err?.code,
        message: err?.message,
        status: err?.response?.status
      });

      if (!transient || last) break;
      await sleep(baseDelayMs * (attempt + 1));
    }
  }
  throw lastErr;
}

function logOk(label, startedAt, res) {
  const ms = Date.now() - startedAt;
  const enc = res?.headers?.['content-encoding'];
  const len = res?.headers?.['content-length'];
  console.log(`[MOODLE][${label}] ok ms=${ms} status=${res.status} enc=${enc} len=${len}`);
}

/* ======================================================================
   1) USERS
   ====================================================================== */

export const queryMoodleUser = async (emailRaw) => {
  const email = normalizeEmail(emailRaw);

  const params = new URLSearchParams();
  params.append('moodlewsrestformat', 'json');
  params.append('wsfunction', 'core_user_get_users');
  params.append('wstoken', process.env.MDL_TOKEN);
  params.append('criteria[0][key]', 'email');
  params.append('criteria[0][value]', email);

  const startedAt = Date.now();
  // GET → safe to retry
  const res = await withRetry(
    () => moodleHttp.get(WebServiceUrl, { params }),
    { retries: 2, label: 'core_user_get_users' }
  );
  logOk('core_user_get_users', startedAt, res);

  const payload = res.data;
  if (!payload || typeof payload !== 'object' || !('users' in payload)) {
    // If Moodle returned something unexpected, treat as error (don’t pretend empty)
    throw new Error('Invalid Moodle response for core_user_get_users');
  }
  return res; // keep your original behavior (return full axios response)
};

export const createMoodleUser = async (user) => {
  const params = new URLSearchParams();
  params.append('moodlewsrestformat', 'json');
  params.append('wsfunction', 'core_user_create_users');
  params.append('wstoken', process.env.MDL_TOKEN);
  params.append('users[0][username]', user.username);
  params.append('users[0][createpassword]', 1);
  params.append('users[0][firstname]', user.firstname);
  params.append('users[0][lastname]', user.lastname);
  params.append('users[0][institution]', user.institution);
  params.append('users[0][country]', user.country);
  params.append('users[0][phone1]', user.phone);
  params.append('users[0][email]', normalizeEmail(user.email));
  params.append('users[0][idnumber]', 'AUTOGENERATEDID002');
  params.append('users[0][description]', 'auto-generated');
  params.append('users[0][lang]', 'en');

  // POST → no retry by default (avoid duplicates)
  const startedAt = Date.now();
  const res = await moodleHttp.post(WebServiceUrl, null, { params });
  logOk('core_user_create_users', startedAt, res);

  if (isMoodleException(res.data)) {
    throw new Error(`[MOODLE ERROR] ${res.data.message} (${res.data.errorcode})`);
  }
  return res;
};

/* ======================================================================
   2) ENROLLMENT / EXTEND
   ====================================================================== */

// ¿Usuario está en el curso? (activo o suspendido)
// IMPORTANT CHANGE: do NOT convert transport errors into "false" silently
export const isUserInCourseAnyStatus = async (userid, courseid) => {
  const uid = Number(userid);
  const cid = Number(courseid);

  const params = new URLSearchParams();
  params.append('moodlewsrestformat', 'json');
  params.append('wsfunction', 'core_enrol_get_enrolled_users');
  params.append('wstoken', process.env.MDL_TOKEN);
  params.append('courseid', cid);
  params.append('options[0][name]', 'onlyactive');
  params.append('options[0][value]', 0);

  const startedAt = Date.now();
  try {
    const res = await withRetry(
      () => moodleHttp.get(WebServiceUrl, { params }),
      { retries: 2, label: 'core_enrol_get_enrolled_users' }
    );
    logOk('core_enrol_get_enrolled_users', startedAt, res);

    const payload = res.data;

    if (isMoodleException(payload)) {
      console.error('[MOODLE ERROR] core_enrol_get_enrolled_users:', payload.message, payload.errorcode);
      return false;
    }
    if (!Array.isArray(payload)) {
      throw new Error('Invalid enrollment payload from Moodle (expected array)');
    }
    return payload.some(u => Number(u.id) === uid);
  } catch (err) {
    console.error('[HTTP ERROR] core_enrol_get_enrolled_users:', err?.message || err);
    throw err;
  }
};

/**
 * Extend via custom local_cscampus plugin.
 * Edits the oldest enrollment regardless of enrollment method.
 */
async function _extendViaPlugin(userid, courseid, timeend) {
  const params = new URLSearchParams();
  params.append('moodlewsrestformat', 'json');
  params.append('wsfunction', 'local_cscampus_extend_enrollment');
  params.append('wstoken', process.env.MDL_TOKEN);
  params.append('userid', userid);
  params.append('courseid', courseid);
  params.append('timeend', timeend);

  const startedAt = Date.now();
  const res = await moodleHttp.post(WebServiceUrl, null, { params });
  logOk('local_cscampus_extend_enrollment', startedAt, res);

  const data = res.data;
  if (isMoodleException(data)) {
    throw new Error(`[MOODLE ERROR] ${data.message} (${data.errorcode})`);
  }
  if (data && data.success === false) {
    throw new Error(`[PLUGIN ERROR] ${data.message}`);
  }
  return res;
}

/**
 * Fallback: extend via enrol_manual_enrol_users.
 * Only updates existing manual enrollments; creates a new one otherwise.
 */
async function _extendViaManualEnrol(userid, courseid, timeend) {
  const params = new URLSearchParams();
  params.append('moodlewsrestformat', 'json');
  params.append('wsfunction', 'enrol_manual_enrol_users');
  params.append('wstoken', process.env.MDL_TOKEN);
  params.append('enrolments[0][roleid]', 5);
  params.append('enrolments[0][userid]', userid);
  params.append('enrolments[0][courseid]', courseid);
  params.append('enrolments[0][timestart]', Math.floor(Date.now() / 1000));
  params.append('enrolments[0][timeend]', timeend);

  const startedAt = Date.now();
  const res = await moodleHttp.post(WebServiceUrl, null, { params });
  logOk('enrol_manual_enrol_users (extendEnrollment fallback)', startedAt, res);

  const data = res.data;
  if (isMoodleException(data)) {
    throw new Error(`[MOODLE ERROR] ${data.message} (${data.errorcode})`);
  }
  return res;
}

export const extendEnrollment = async ({ userid, courseid, timeend }) => {
  // Try the custom plugin first (edits the oldest enrollment, any method)
  try {
    return await _extendViaPlugin(userid, courseid, timeend);
  } catch (err) {
    console.warn('[MOODLE] Plugin extend failed, falling back to enrol_manual_enrol_users:', err?.message);
  }
  // Fallback: standard manual enrol API
  return _extendViaManualEnrol(userid, courseid, timeend);
};

export const enrollMoodleuser = async (userId, courseId, timestart, timeend) => {
  const params = new URLSearchParams();
  params.append('moodlewsrestformat', 'json');
  params.append('wsfunction', 'enrol_manual_enrol_users');
  params.append('wstoken', process.env.MDL_TOKEN);
  params.append('enrolments[0][roleid]', '5');
  params.append('enrolments[0][userid]', userId);
  params.append('enrolments[0][courseid]', courseId);
  params.append('enrolments[0][timestart]', timestart);
  params.append('enrolments[0][timeend]', timeend);
  params.append('enrolments[0][suspend]', '0');

  const startedAt = Date.now();
  const res = await moodleHttp.post(WebServiceUrl, null, { params });
  logOk('enrol_manual_enrol_users (enrollMoodleuser)', startedAt, res);

  if (isMoodleException(res.data)) {
    throw new Error(`[MOODLE ERROR] ${res.data.message} (${res.data.errorcode})`);
  }
  return res;
};

/* ======================================================================
   3) COURSES
   ====================================================================== */

export const getCourseInfoById = async (courseid) => {
  const cid = Number(courseid);

  const params = new URLSearchParams();
  params.append('moodlewsrestformat', 'json');
  params.append('wsfunction', 'core_course_get_courses_by_field');
  params.append('wstoken', process.env.MDL_TOKEN);
  params.append('field', 'id');
  params.append('value', cid);

  const startedAt = Date.now();
  try {
    const res = await withRetry(
      () => moodleHttp.get(WebServiceUrl, { params }),
      { retries: 2, label: 'core_course_get_courses_by_field' }
    );
    logOk('core_course_get_courses_by_field', startedAt, res);

    const payload = res.data;
    if (isMoodleException(payload)) return null;
    const course = Array.isArray(payload?.courses) ? payload.courses[0] : null;
    return course || null;
  } catch (err) {
    console.error('[HTTP ERROR] core_course_get_courses_by_field:', err?.message || err);
    return null;
  }
};

export const getCourseNameById = async (courseid) => {
  const course = await getCourseInfoById(courseid);
  return course?.fullname || `Curso ${courseid}`;
};

/* ======================================================================
   4) GROUPS
   ====================================================================== */

export const getCourseGroups = async (courseid) => {
  const cid = Number(courseid);

  const params = new URLSearchParams();
  params.append('moodlewsrestformat', 'json');
  params.append('wsfunction', 'core_group_get_course_groups');
  params.append('wstoken', process.env.MDL_TOKEN);
  params.append('courseid', cid);

  const startedAt = Date.now();
  try {
    const res = await withRetry(
      () => moodleHttp.get(WebServiceUrl, { params }),
      { retries: 2, label: 'core_group_get_course_groups' }
    );
    logOk('core_group_get_course_groups', startedAt, res);

    const payload = res.data;

    if (isMoodleException(payload)) {
      console.error('[MOODLE ERROR] core_group_get_course_groups:', payload.message, payload.errorcode);
      return [];
    }
    if (!Array.isArray(payload)) return [];
    return payload;
  } catch (err) {
    console.error('[HTTP ERROR] core_group_get_course_groups:', err?.message || err);
    return [];
  }
};

export const getHotmartGroupId = async (courseid) => {
  try {
    const groups = await getCourseGroups(courseid);
    const hotmartGroup = groups.find(group =>
      group.name && group.name.toLowerCase().includes('hotmart')
    );
    return hotmartGroup ? hotmartGroup.id : null;
  } catch (error) {
    console.error(`Error buscando grupo Hotmart en curso ${courseid}:`, error);
    return null;
  }
};

export const addUserToMoodleGroup = async (userId, groupid) => {
  const params = new URLSearchParams();
  params.append('moodlewsrestformat', 'json');
  params.append('wsfunction', 'core_group_add_group_members');
  params.append('wstoken', process.env.MDL_TOKEN);
  params.append('members[0][groupid]', groupid);
  params.append('members[0][userid]', userId);

  const startedAt = Date.now();
  const res = await moodleHttp.post(WebServiceUrl, null, { params });
  logOk('core_group_add_group_members', startedAt, res);

  if (isMoodleException(res.data)) {
    throw new Error(`[MOODLE ERROR] ${res.data.message} (${res.data.errorcode})`);
  }
  return res;
};

// Método principal (2 llamadas): ids → nombres
async function _getGroupNames_viaGroupsAPI(userid, courseid) {
  const params = new URLSearchParams();
  params.append('moodlewsrestformat', 'json');
  params.append('wsfunction', 'core_group_get_course_user_groups');
  params.append('wstoken', process.env.MDL_TOKEN);
  params.append('userid', Number(userid));
  params.append('courseid', Number(courseid));

  try {
    const res = await withRetry(
      () => moodleHttp.get(WebServiceUrl, { params }),
      { retries: 2, label: 'core_group_get_course_user_groups' }
    );
    const payload = res.data;
    if (isMoodleException(payload)) return [];

    const groupIds = Array.isArray(payload?.groups) ? payload.groups.map(g => g.id) : [];
    if (!groupIds.length) return [];

    const params2 = new URLSearchParams();
    params2.append('moodlewsrestformat', 'json');
    params2.append('wsfunction', 'core_group_get_groups');
    params2.append('wstoken', process.env.MDL_TOKEN);
    groupIds.forEach((gid, idx) => params2.append(`groupids[${idx}]`, gid));

    const res2 = await withRetry(
      () => moodleHttp.get(WebServiceUrl, { params: params2 }),
      { retries: 2, label: 'core_group_get_groups' }
    );
    const payload2 = res2.data;
    if (isMoodleException(payload2)) return [];

    const names = Array.isArray(payload2?.groups)
      ? payload2.groups.map(g => (g?.name ?? '')).filter(Boolean)
      : [];
    return names;
  } catch {
    return [];
  }
}

// Fallback: leer nombres desde core_enrol_get_enrolled_users
async function _getGroupNames_viaEnrolAPI(userid, courseid) {
  const uid = Number(userid);
  const cid = Number(courseid);

  const params = new URLSearchParams();
  params.append('moodlewsrestformat', 'json');
  params.append('wsfunction', 'core_enrol_get_enrolled_users');
  params.append('wstoken', process.env.MDL_TOKEN);
  params.append('courseid', cid);
  params.append('options[0][name]', 'onlyactive');
  params.append('options[0][value]', 0);

  try {
    const res = await withRetry(
      () => moodleHttp.get(WebServiceUrl, { params }),
      { retries: 2, label: 'core_enrol_get_enrolled_users (groups fallback)' }
    );
    const payload = res.data;
    if (!Array.isArray(payload)) return [];

    const me = payload.find(u => Number(u.id) === uid);
    const groups = Array.isArray(me?.groups) ? me.groups : [];
    return groups.map(g => (g?.name ?? '')).filter(Boolean);
  } catch {
    return [];
  }
}

export const getUserGroupNamesInCourse = async (userid, courseid) => {
  let names = await _getGroupNames_viaGroupsAPI(userid, courseid);
  if (!names.length) {
    names = await _getGroupNames_viaEnrolAPI(userid, courseid);
  }
  return names.map(n => String(n).trim()).filter(Boolean);
};
